#!/bin/sh

# Example usage
# sh add-user naikus@gmail.com password Aniket Naik

TOKEN=`curl -v -X POST \
    -d 'username=superuser@example.com&password=password' \
    http://localhost:8080/api/authentication`

curl -v -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
            "email": "'$1'",
            "password": "'$2'",
            "firstName": "'$3'",
            "lastName": "'$4'",
            "role": {
                "name": "appuser"
            }
        }' \
    http://localhost:8080/api/users