#!/bin/sh

# Example usage
# sh get-users

TOKEN=`curl -v -X POST \
    -d 'username=superuser@example.com&password=password' \
    http://localhost:8080/api/authentication`

curl -v -X GET -H "Authorization: Bearer $TOKEN"  http://localhost:8080/api/users
